config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'ramen_reviews#index'

  get '/hall_of_fame', to: 'restaurants#hall_of_fame'

  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :restaurants do
    resource :favorite, module: :restaurants
    collection do
      get :map
    end
  end
  resources :ramen_reviews do
    resource :favorite, module: :ramen_reviews
    resource :like
  end
end

app/views/shared/_advanced_search.haml
.search-container
  = search_form_for @q, url: root_path, method: :get, data: { controller: 'advanced-search', turbo_frame: 'search' } do |f|
    .main-search
      .search-input-wrapper
        = f.search_field :soup_or_restaurant_name_or_restaurant_jpn_name_or_restaurant_station_or_restaurant_city_or_restaurant_prefecture_cont, placeholder: 'type, location, or name', oninput: 'this.form.requestSubmit()', class: 'search-input'
        = f.hidden_field :view, value: @view_type 
        .search-actions
          .advanced-search-toggle{ data: { 'advanced-search-target': 'toggleButton', action: 'click->advanced-search#toggleAdvancedSearch' } }
            %box-icon{ name: 'slider', size: '20px' }
    .advanced-search-panel{ data: { 'advanced-search-target': 'panel' } }
      .filter-section
        .filter-title Soup Type
        .checkbox-grid
          - RamenReview.soup.options.each do |value, label|
            .checkbox-item
              = check_box_tag "q[soup_in][]", value, params.dig(:q, :soup_in)&.include?(value.to_s), id: "soup_#{value}", class: "checkbox-input", data: { 'advanced-search-target': 'soupCheckbox'}, oninput: 'this.form.requestSubmit()'
              = label_tag "soup_#{value}", label, class: "checkbox-label"
      .panel-footer
        %button.clear-filters{ data: { 'advanced-search-target': 'clearFiltersButton', action: 'click->advanced-search#clearFilters' } } Clear All Filters

app/views/shared/_map.haml
#js-map{ data: { map_target: 'map', map_markers_value: markers }, style: "height: 100vh;" }

app/views/shared/_navbar.haml
.navbar{ data: { controller: 'navbar' } }
  .navbar__logo
    = link_to root_path do
      = image_tag('ramenlogo.png')

  - if current_page?(root_path) || current_page?(ramen_reviews_path)
    = render 'shared/advanced_search'
    .view-switcher
  = form_with url: ramen_reviews_path, method: :get, local: false, class: 'view-toggle-form' do |form|
    -# = form.hidden_field :q, value: params[:q]&.to_unsafe_h&.to_query

    .toggle-switch
      = form.radio_button :view, 'card',
                          checked: @view_type == 'card',
                          id: 'view_card',
                          onchange: 'this.form.requestSubmit()'
      = form.radio_button :view, 'grid',
                          checked: @view_type == 'grid',
                          id: 'view_grid',
                          onchange: 'this.form.requestSubmit()'

      = form.label :view_card, class: 'toggle-option' do
        %box-icon{ name: :card, size: '20px' }
        -# %span Card

      = form.label :view_grid, class: 'toggle-option' do
        %box-icon{ name: :grid, type: :solid, size: '20px'}
        -# %span Grid

      .toggle-slider
  - if current_page?(map_restaurants_url)
    .navbar__search-container
      = search_form_for @q, url: map_restaurants_url,
                      data: { map_target: "form" } do |f|
        = f.search_field :name_cont, placeholder: "Search restaurants...",
                        data: { map_target: 'field', action: 'input->map#search:prevent' },
                        class: 'navbar__search-input'
  .navbar__menu-container{ data: { action: 'click->navbar#toggleDropdown click@window->navbar#closeDropdown' } }
    %box-icon{ name: 'menu', size: '24px' }
    .navbar__dropdown{ data: { navbar_target: 'navlinks' } }
      .navbar__nav-link
        = link_to restaurants_path, class: 'd-flex align-items-center' do
          %box-icon{ name: 'store-alt', size: '20px' }
          %p.navbar__nav-link-text Restaurants
      .navbar__nav-link
        = link_to map_restaurants_url, class: 'd-flex align-items-center' do
          %box-icon{ name: 'map', type: 'solid' }
          %p.navbar__nav-link-text Ramen Map
      .navbar__nav-link
        = link_to hall_of_fame_path, class: 'd-flex align-items-center' do
          %box-icon{ name: 'star', type: 'solid', color: '#e74d30', size: '20px' }
          %p.navbar__nav-link-text Hall of Fame
      .navbar__nav-link
        = link_to new_ramen_review_path, class: 'd-flex align-items-center' do
          %box-icon{ name: 'detail', size: '20px' }
          %p.navbar__nav-link-text New Ramen Review