config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'ramen_reviews#index'

  get '/hall_of_fame', to: 'restaurants#hall_of_fame'

  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :restaurants do
    resource :favorite, module: :restaurants
    collection do
      get :map
    end
  end
  resources :ramen_reviews do
    resource :favorite, module: :ramen_reviews
    resource :like
  end
end

app/controllers/ramen_reviews/favorites_controller.rb
class RamenReviews::FavoritesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_ramen_review

  def update
    if @ramen_review.favorited_by?(current_user)
      @ramen_review.unfavorite(current_user)
    else
      @ramen_review.favorite(current_user)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          dom_id(@ramen_review, :favorite),
          partial: 'ramen_reviews/favorite',
          locals: { ramen_review: @ramen_review, current_user: current_user }
        )
      end
    end
  end

  private

  def set_ramen_review
    @ramen_review = RamenReview.find(params[:ramen_review_id])
  end
end

app/controllers/ramen_reviews_controller.rb
class RamenReviewsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_selected_restaurant, only: %i[new edit]
  before_action :set_ramen_review, only: %i[show edit update]

  def index
    @q = RamenReview.includes(:review_images).ransack(params[:q])
    @pagy, @ramen_reviews = pagy(@q.result.includes(:restaurant).distinct(true))
  end

  def new
    @ramen_review = RamenReview.new
    @review_image = @ramen_review.review_images.build
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result.distinct(true).limit(5)
    render partial: 'restaurant_search_results', restaurants: @restaurants if turbo_frame_request?
  end

  def show
    @restaurant = @ramen_review.restaurant
    if @restaurant.geocoded?
      @marker = [{
          lat: @restaurant.latitude,
          lng: @restaurant.longitude,
          color: helpers.star_color(@restaurant.average_score),
          average_score: @restaurant.average_score
      }]
    end
  end

  def edit
    @ramen_review = RamenReview.includes(review_images: {image_attachment: :blob}).find(params[:id])
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result.distinct(true).limit(5)
  end

  def create
    @ramen_review = RamenReview.new(ramen_review_params)
    if @ramen_review.save
      redirect_to ramen_review_url(@ramen_review), notice: 'sucessfully created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @ramen_review.update(ramen_review_params)
      redirect_to ramen_review_url(@ramen_review), notice: 'succesfully updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def ramen_review_params
    params.require(:ramen_review).permit(
      :soup, :score, :review, :price, :restaurant_id, :content,
      review_images_attributes: [:id, :blob_signed_id, :position, :_destroy]
    )
  end

  def set_ramen_review
    @ramen_review = RamenReview.find(params[:id])
  end

  def set_selected_restaurant
    @selected_restaurant = Restaurant.find(params[:selected_restaurant_id]) if params[:selected_restaurant_id].present?
  end
end

app/views/ramen_reviews/_favorite.html.haml
= turbo_frame_tag ramen_review, :favorite, style: 'flex: 1;' do
  = link_to ramen_review_favorite_path(ramen_review),
            class: 'review-card__btn review-card__btn--secondary',
            method: :patch,
            data: { turbo_method: :patch } do
    %box-icon.review-card__btn-icon{ favorite_icon_hash(ramen_review, current_user) }
    - if ramen_review.favorited_by?(current_user)
      Saved
    - else
      Save

app/views/ramen_reviews/_form.haml
.container.mt-4{ data: { controller: 'ramen-reviews--form'}}
  .row.mb-4
    %h5 Select Restaurant
    = search_form_for @q, url: @ramen_review.persisted? ? edit_ramen_review_url : new_ramen_review_url, method: :get, data: { turbo_frame: 'restaurant-search-results', 'ramen-reviews--form-target': 'searchForm' } do |sff|
      = sff.search_field :name_or_jpn_name_or_station_or_city_or_prefecture_cont,
        placeholder: 'Search for restaurant by name or location',
        class: 'form-control',
        oninput: 'this.form.requestSubmit()'
      = render 'restaurant_search_results', restaurants: @restaurants
    .mt-2{ data: { 'ramen-reviews--form-target': 'selectedRestaurantContainer' } }
      - selected_restaurant = @selected_restaurant || @ramen_review.restaurant
      = turbo_frame_tag :selected_restaurant do
        - if selected_restaurant.present?
          = render 'restaurant_search_result', restaurant: selected_restaurant
    = link_to 'Add Restaurant', new_restaurant_path, id: :new_restaurant, data: { turbo_stream: true }
  = simple_form_for @ramen_review, data: { turbo: false } do |f|
    = turbo_frame_tag :selected_restaurant_id_field do
      = render 'restaurant_id_field', restaurant_id: @ramen_review&.restaurant_id || @selected_restaurant&.id

    %label.form-label Upload images
    .image-upload-area.mb-4{ data: { controller: 'upload', sortable_target: 'container', upload_target: 'container' } }
      .upload-button.mb-2
        %label.btn.btn-outline-primary
          Drag and drop files here or click to upload
          = file_field_tag :images, multiple: true, direct_upload: true, class: 'is-hidden', data: { upload_target: 'input', action: 'change->upload#handleFiles' }

      .preview-container{ data: { controller: 'sortable', sortable_target: 'container' } }
        - if @ramen_review.persisted? && @ramen_review.review_images.any?
          = f.fields_for :review_images, @ramen_review.review_images.order(:position) do |ff, index|
            .preview.card.mb-2{ data: { upload_target: 'preview', sortable_target: 'item', image_index: ff.index } }
              - if ff.object.image.attached?
                = image_tag ff.object.image
              .card-body.p-2
                %button.btn.btn-sm.btn-danger.position-absolute.top-0.end-0.m-1{ type: 'button', data: { action: 'click->upload#removeImage' } } ×
                = ff.hidden_field :id
                = ff.hidden_field :position, value: index, data: { sortable_target: 'position' }
                = ff.hidden_field :_destroy, value: "0", data: { upload_target: 'destroyField' }
      = render 'review_images/preview_card'

    = f.rich_text_area :content
    .mt-2
      = f.input :soup, as: :select, input_html: { class: 'form-select' }
    .mt-2
      = f.input :score, as: :select, collection: RamenReview::POSSIBLE_SCORES, selected: 3.0, include_blank: false, input_html: { class: 'form-select' }
    .ramen-reviews__button-container
      = f.submit submit_button_text, class: 'ramen-button'

app/views/ramen_reviews/_restaurant_id_field.html.haml
= hidden_field_tag 'ramen_review[restaurant_id]', restaurant_id, data: { 'ramen-reviews--form-target': 'restaurantId' }

app/views/ramen_reviews/_restaurant_search_result.haml
.restaurant-item{ role: 'button',
  data: {
    restaurant_id: restaurant.id,
    restaurant_name: restaurant.name,
    action: 'click->ramen-reviews--form#selectRestaurant'
  }
}
  .restaurant-search-result__info{ class: "#{'is-selected' if @restaurant.present? || @ramen_review.restaurant.present?}" }
    .restaurant-search-result__name= restaurant.name
    .restaurant-search-result__name-jp= restaurant.jpn_name
    .restaurant-search-result__details
      = [restaurant.station, restaurant.prefecture].compact.join(' • ')

app/views/ramen_reviews/_restaurant_search_results.haml
= turbo_frame_tag 'restaurant-search-results', data: { 'ramen-reviews--form-target': 'searchResults'} do
  .restaurant-results.mt-2
    - if params.dig(:q, :name_or_jpn_name_or_station_or_city_or_prefecture_cont).present?
      - if @restaurants.present?
        - @restaurants.each do |restaurant|
          = render 'restaurant_search_result', restaurant: restaurant
      - else
        .text-muted No restaurants found

app/views/ramen_reviews/_review_card.haml
.review-card__container
  = link_to ramen_review_path(ramen_review) do
    - if ramen_review.review_images.first&.image.present?
      = image_tag(ramen_review.review_images.first.image)
    .review-card__content
      .d-flex.justify-content-between.align-items-start.mb-12
        .name-container
          .review-card__name-en.mb-4= ramen_review.restaurant.name
          .review-card__name-jp= ramen_review.restaurant.jpn_name
        .d-flex.align-items-center
          - score = ramen_review.score
          - review_card_score_stars(score).each do |star|
            %box-icon{ name: star[:name], type: star[:type], color: star[:color], size: '18px' }
          %p.review-card__score.pl-4= score
      .d-flex.align-items-center.mb-8
        %box-icon.pr-4{ name: 'train', type: 'solid', size: '18px'}
        %span= "#{ramen_review.restaurant.station}, #{ramen_review.restaurant.prefecture}"

      .review-card__footer
        %span.review-card__icon
          = ramen_review.soup
        %span.review-card__created-at
          = ramen_review.created_at.strftime('%Y/%m/%d')

app/views/ramen_reviews/_review_grid_item.haml
= link_to ramen_review_path(ramen_review), class: 'review-grid-item' do
  .review-grid-image
    - if ramen_review.review_images.any?
      = image_tag ramen_review.review_images.first.image,
                  alt: ramen_review.restaurant.name,
                  class: 'grid-image'
    - else
      .placeholder-image
        = icon 'utensils' # or whatever placeholder you prefer

  .review-grid-overlay
    .restaurant-name= truncate(ramen_review.restaurant.name, length: 20)
    .d-flex.align-items-center
      - score = ramen_review.score
      - review_card_score_stars(score).each do |star|
        %box-icon{ name: star[:name], type: star[:type], color: star[:color], size: '18px' }
      %p.review-card__score.pl-4= score

app/views/ramen_reviews/edit.haml
.ramen-reviews__header-container
  .ramen-reviews__header-content
    %h1.ramen-reviews__title Edit Your Review
    %p.ramen-reviews__subtitle Update your dining experience details
    .ramen-reviews__decorative-bars
      .ramen-reviews__bar.ramen-reviews__bar.is-small
      .ramen-reviews__bar.ramen-reviews__bar.is-large
      .ramen-reviews__bar.ramen-reviews__bar.is-small
= render 'form'

app/views/ramen_reviews/index.haml
= render 'shared/navbar'
.view-switcher
  = form_with url: ramen_reviews_path, method: :get, local: false do |form|
    = form.select :view,
                  options_for_select([['Card View', 'card'], ['Grid View', 'grid']], @view_type),
                  {},
                  { onchange: 'this.form.requestSubmit()', class: 'view-select' }
= turbo_frame_tag 'search', target: "_top" do
  = turbo_frame_tag :ramen_reviews_page, @pagy.page do
    .ramen-reviews__container{ class: "ramen-reviews__container-#{@view_type}" }
      - @ramen_reviews.each do |ramen_review|
        - if @view_type == 'grid'
          = render 'review_grid_item', ramen_review: ramen_review
        - else
          = render 'review_card', ramen_review: ramen_review

  - if @pagy.next
    = turbo_frame_tag :ramen_reviews_page, @pagy.next, src: ramen_reviews_path(page: @pagy.next, view: view_type, q: params[:q]), loading: :lazy do
      = tag.div 'Loading...'

app/views/ramen_reviews/index.turbo_stream.html.haml
- turbo_stream.replace 'reviews_container' do
  = render 'reviews_container', ramen_reviews: @ramen_reviews, view_type: @view_type, pagy: @pagy

app/views/ramen_reviews/new.haml
.ramen-reviews__header-container
  .ramen-reviews__header-content
    %h1.ramen-reviews__title Post Your Review
    %p.ramen-reviews__subtitle Share your dining experience with the community
    .ramen-reviews__decorative-bars
      .ramen-reviews__bar.ramen-reviews__bar.is-small
      .ramen-reviews__bar.ramen-reviews__bar.is-large
      .ramen-reviews__bar.ramen-reviews__bar.is-small
= render 'form'

app/views/ramen_reviews/show.haml
= render 'shared/navbar'

.review-card__container.review-card__container--show
  - if @ramen_review.review_images.present?
    .review-card__gallery
      .swiper{ data: { controller: 'swiper', swiper_target: 'swiper' } }
        .swiper-wrapper
          - @ramen_review.review_images.each do |review_image|
            .swiper-slide
              = image_tag(review_image.image)
        .swiper-pagination{ data: { swiper_target: 'pagination' } }

  .review-card__content
    .review-card__header
      .review-card__name= @ramen_review.restaurant.name
      .review-card__name-jp= @ramen_review.restaurant.jpn_name

      .review-card__meta
        .review-card__rating
          .review-card__stars
            - score = @ramen_review.score
            - review_card_score_stars(score).each do |star|
              %box-icon{ name: star[:name], type: star[:type], color: star[:color], size: '18px' }
          .review-card__rating-value= score

        = link_to '#anchor-map' do
          .review-card__location
            %box-icon{ name: "map-pin", color: "#6c757d", type: "regular", size: '18px' }
            = @ramen_review.restaurant.city
            %box-icon{ name: 'train', color: "#6c757d", type: 'regular', size: '18px'}
            = "#{@ramen_review.restaurant.station} Station"

        .review-card__details
          .review-card__soup
            %box-icon{ name: "bowl-hot", color: "#6c757d", type: "regular", size: '18px' }
            = @ramen_review.soup.capitalize
          .review-card__price
            %box-icon{ name: "yen", color: "#6c757d", type: "regular", size: '18px' }
            = @ramen_review.price

        .review-card__date= @ramen_review.created_at.strftime("%Y/%m/%d")

    .review-card__review
      .review-card__review-text
        = simple_format(@ramen_review.review)

  #anchor-map.review-card__map-container
    %div{ data: { controller: 'map', map_markers_value: @marker.to_json } }
      #js-map{ data: { map_target: 'map' }, style: "height: 200px;" }

  .review-card__actions
    -# .review-card__btn.review-card__btn--secondary
    = render 'favorite', ramen_review: @ramen_review
    %button.review-card__btn.review-card__btn--primary
      -# %box-icon{ name: 'share', color: 'white', type: 'regular', size: '24px' }
      %svg.review-card__btn-icon{ viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", 'stroke-width': "2" }
        %circle{ cx: "18", cy: "5", r: "3" }
        %circle{ cx: "6", cy: "12", r: "3" }
        %circle{ cx: "18", cy: "19", r: "3" }
        %path{ d: "M8.59 13.51l6.83 3.98M15.41 6.51l-6.82 3.98" }
      Share