config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root 'ramen_reviews#index'

  get '/hall_of_fame', to: 'restaurants#hall_of_fame'

  mount MissionControl::Jobs::Engine, at: "/jobs"

  resources :restaurants do
    resource :favorite, module: :restaurants
    collection do
      get :map
    end
  end
  resources :ramen_reviews do
    resource :favorite, module: :ramen_reviews
    resource :like
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  include Favoritable
  extend Enumerize
  has_many :ramen_reviews, dependent: :destroy

  validates :name, presence: true
  validates :jpn_name, presence: true
  validates :address, presence: true
  validates :prefecture, presence: true

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  serialize :days_closed, type: Array, coder: JSON
  enumerize :days_closed, in: %i[monday tuesday wednesday thursday friday saturday sunday holiday none], multiple: true, default: []

  def update_average_score
    update(average_score: ramen_reviews.average(:score).round(2))
  end

  def display_images
    first_images = fetch_first_images.compact
    additional_images = fetch_additional_images(first_images) if first_images.size < 3
    (first_images + additional_images.to_a).uniq(&:id)
  end

  private

  def fetch_first_images
    ramen_reviews.order(id: :desc)
                 .flat_map { |ramen_review| ramen_review.review_images.order(id: :desc).first }
                 .take(3)
  end

  def fetch_additional_images(first_images)
    all_images = ramen_reviews.flat_map { |review| review.review_images.order(id: :desc) }
    remaining_images = all_images - first_images
    remaining_images.first(3 - first_images.size)
  end

  def self.ransackable_attributes(auth_object = nil)
    %w[title content soup name jpn_name station city prefecture]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[ramen_reviews]
  end
end

app/controllers/restaurants/favorites_controller.rb
class Restaurants::FavoritesController < ApplicationController
  include ActionView::RecordIdentifier
  before_action :authenticate_user!
  before_action :set_restaurant

  def update
    if @restaurant.favorited_by?(current_user)
      @restaurant.unfavorite(current_user)
    else
      @restaurant.favorite(current_user)
    end

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.replace(
          dom_id(@restaurant, :favorite),
          partial: 'restaurants/favorite',
          locals: { restaurant: @restaurant, current_user: current_user }
        )
      end
    end
  end

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: :show
  before_action :store_referer, only: :new

  def index
    @pagy, @restaurants = pagy(Restaurant.all)
  end

  def new
    @restaurant = Restaurant.new
  end

  def show; end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurant_url(@restaurant) }
        format.turbo_stream { @selected_restaurant = @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.turbo_stream { render :new }
      end
    end
  end

  def map
    @q = Restaurant.ransack(params[:q])
    @restaurants = @q.result
    @markers = @restaurants.geocoded.map do |restaurant|
      {
        id: restaurant.id,
        lat: restaurant.latitude,
        lng: restaurant.longitude,
        color: helpers.star_color(restaurant.average_score),
        name: restaurant.name,
        jpn_name: restaurant.jpn_name,
        average_score: restaurant.average_score,
        infowindow: render_to_string(partial: 'restaurants/info_window', locals: { restaurant:, review_images: restaurant.ramen_reviews.flat_map(&:review_images).take(10) })
      }
    end

    puts "Markers count: #{@markers.count}"
    puts "First marker: #{@markers.first.inspect}" if @markers.any?
    puts "=== END MAP ACTION ==="

    respond_to do |format|
      format.html
      format.json { render json: { markers: @markers } }
    end
  end

  def hall_of_fame; end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:address, :name, :jpn_name, :date_opened, :station, :city, :prefecture, days_closed: [])
  end

  def store_referer
    session[:back_path] = request.referer if request.referer.present?
  end

  def return_url(restaurant)
    if session[:back_path]&.include?('ramen_reviews/new')
      session.delete(:back_path)
      new_ramen_review_path(selected_restaurant_id: restaurant.id)
    else
      restaurant_path(restaurant)
    end
  end
end

app/views/restaurants/_favorite.haml
= turbo_frame_tag restaurant, :favorite do
  = button_to restaurant_favorite_path(restaurant), form_class: 'favorite__button', method: :patch do
    %box-icon{ favorite_icon_hash(restaurant, current_user) }

app/views/restaurants/_form.html.haml
.container.mt-4
  = simple_form_for restaurant, id: (restaurant.new_record? ? :new_restaurant : :edit_restaurant) do |f|
    = f.error_notification
    .mb-3
      = f.input :name, input_html: { class: 'form-control' }
    .mb-3
      = f.input :jpn_name, input_html: { class: 'form-control' }
    .mb-3
      = f.label :date_opened, input_html: { class: 'form-label' }
      = f.input :date_opened, as: :date, label: false, start_year: Date.current.year, end_year: 1900, include_blank: true, allow_blank: true, wrapper_html: { class: 'd-flex' }, input_html: { class: 'form-select' }
    .mb-3
      = f.input :station, input_html: { class: 'form-control' }
    .mb-3
      = f.input :city, input_html: { class: 'form-control' }
    .mb-3
      = f.input :prefecture, input_html: { class: 'form-control' }
    .mb-3
      = f.input :address, input_html: { class: 'form-control' }
    .mb-3
      = f.input :days_closed, as: :check_boxes, collection: Restaurant.days_closed.options,  label: 'Days Closed', item_wrapper_class: 'form-check', include_hidden: false, input_html: { class: 'form-check-input' }
    .mb-4.d-flex.align-items-center.justify-content-center
      = f.submit class: 'btn btn-primary'

app/views/restaurants/_info_window.haml
.info-window__image-container.swiper{ data: { controller: 'swiper', swiper_target: 'swiper' } }
  - if review_images.present?
    .swiper-wrapper
      - review_images.each do |review_image|
        .swiper-slide
          = image_tag(review_image.image)
    .swiper-pagination{ data: { swiper_target: 'pagination' } }
%div
  = restaurant.name
%div
  = restaurant.jpn_name
%div
  = format('%.2f' % restaurant.average_score)
  - review_card_score_stars(restaurant.average_score).each do |star|
    %box-icon.bx-sm{ name: star[:name], type: star[:type], color: star[:color], size: 'xs' }
%div
  = restaurant.year_opened
%div
  = "Reviews: #{restaurant.ramen_reviews.count}"

app/views/restaurants/_info_window.html.haml
.modern-info-window
  .info-window-header
    .info-window-swiper.swiper{ data: { controller: 'swiper', swiper_target: 'swiper' } }
      - if review_images.present?
        .swiper-wrapper
          - review_images.each do |review_image|
            .swiper-slide.info-window-slide
              = image_tag(review_image.image.variant(resize_to_fill: [280, 280]), alt: "#{restaurant.name} review photo")
        .swiper-pagination{ data: { swiper_target: 'pagination' } }
      - else
        .info-window-slide
          no image
          -# = image_tag('ramen-placeholder.jpg',
          -#            alt: restaurant.name,
          -#            class: 'placeholder-image')
    .info-window-gradient

  .info-window-content
    %div.restaurant-name
      = restaurant.name
    %div.restaurant-jpn-name
      = restaurant.jpn_name
    .rating-section
      .rating-score{ style: "color:#{star_color(restaurant.average_score)};"}= format('%.2f', restaurant.average_score)
      .rating-stars
        - review_card_score_stars(restaurant.average_score).each do |star|
          %box-icon{ name: star[:name], type: star[:type], color: star[:color], size: '16px' }
      .info-window-reviews
        = link_to restaurant_path(restaurant.id), class: 'restaurant-card__reviews-link' do
          %box-icon{ name: 'message-rounded-dots', type: 'solid', color: '#888888' }
          %span= restaurant.ramen_reviews.count
    .info-row
      %div.info-label
        %box-icon{ name: 'train', color: '#888', size: '20px' }
      %div.info-value
        = restaurant.station
    .info-row
      %box-icon{ name: 'calendar-x', color: '#888', size: '20px' }
      %span.restaurant-card__days-closed-text= restaurant.days_closed.join(', ')

app/views/restaurants/_restaurant_card.haml
= link_to restaurant_path(restaurant), class: 'restaurant-card__link' do
  .restaurant-card__container
    %h3.restaurant-card__title= restaurant.name
    %h4.restaurant-card__title-jpn= restaurant.jpn_name
    .restaurant-card__info
      %p= "#{restaurant.station}, #{restaurant.prefecture}"
    .restaurant-card__images-container
      - restaurant.display_images.each do |display_image|
        .restaurant-card__display-image
          = image_tag display_image.image
    .d-flex.align-items-center.pt-2
      - score = restaurant.average_score
      .d-flex
        - review_card_score_stars(score).each do |star|
          %box-icon{ name: star[:name], type: star[:type], color: star[:color] }
        .restaurant-card__score= format('%.2f', score)
      = link_to restaurant_path(restaurant.id), class: 'restaurant-card__reviews-link' do
        %box-icon{ name: 'message-rounded-dots', type: 'solid', color: '#beb99b' }
        %span= restaurant.ramen_reviews.count
      .restaurant-card__bookmark{ onclick: 'event.stopPropagation();' }
        = render 'favorite', restaurant: restaurant, current_user: current_user
    .d-flex.align-items-center.pt-2
      %box-icon{ name: 'calendar-x', color: '#beb99b' }
      %span.restaurant-card__days-closed-text= restaurant.days_closed.join(', ')

app/views/restaurants/create.turbo_stream.haml
= turbo_stream.replace :new_restaurant do
  = link_to 'Add Restaurant', new_restaurant_path, id: :new_restaurant, data: { turbo_stream: true }
= turbo_stream.replace :selected_restaurant, partial: 'ramen_reviews/restaurant_search_result', locals: { restaurant: @restaurant}
= turbo_stream.replace :selected_restaurant_id_field, partial: 'ramen_reviews/restaurant_id_field', locals: { restaurant_id: @restaurant.id }

app/views/restaurants/index.haml
.restaurants__container
  = turbo_frame_tag :restauarnts_page, @pagy.page do
    - @restaurants.each do |restaurant|
      = render 'restaurant_card', restaurant: restaurant
    - if @pagy.next
      = turbo_frame_tag :resetaurants_page, @pagy.next, src: restaurants_path(page: @pagy.next), loading: :lazy do
        = tag.div 'Loading...'

app/views/restaurants/map.haml
%div{ data: { controller: 'map', map_markers_value: @markers.to_json } }
  = render '/shared/navbar'
  #js-map{ data: { map_target: 'map' }, style: "height: 100vh;" }

app/views/restaurants/new.haml
.container.mt-4
  = simple_form_for @restaurant, data: { turbo: false } do |f|
    = f.error_notification
    .mb-3
      = f.input :name, input_html: { class: 'form-control' }
    .mb-3
      = f.input :jpn_name, input_html: { class: 'form-control' }
    .mb-3
      = f.label :date_opened, input_html: { class: 'form-label' }
      = f.input :date_opened, as: :date, label: false, start_year: Date.current.year, end_year: 1900, include_blank: true, allow_blank: true, wrapper_html: { class: 'd-flex' }, input_html: { class: 'form-select' }
    .mb-3
      = f.input :station, input_html: { class: 'form-control' }
    .mb-3
      = f.input :city, input_html: { class: 'form-control' }
    .mb-3
      = f.input :prefecture, input_html: { class: 'form-control' }
    .mb-3
      = f.input :address, input_html: { class: 'form-control' }
    .mb-3
      = f.input :days_closed, as: :check_boxes, collection: Restaurant.days_closed.options,  label: 'Days Closed', item_wrapper_class: 'form-check', include_hidden: false, input_html: { class: 'form-check-input' }
    .mb-4.d-flex.align-items-center.justify-content-center
      = f.submit class: 'btn btn-primary'

app/views/restaurants/new.turbo_stream.haml
= turbo_stream.replace :new_restaurant, partial: 'restaurants/form', locals: { restaurant: @restaurant }

app/views/restaurants/show.haml
%h1= @restaurant.name